import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Header from "../components/header/header";
import Loading from "./loading";
import { Suspense } from "react";
import { MdbProvider } from "@/providers/MoviesContext/mdbContext";
import { getGenres } from "@/services/utils";

const roboto = Roboto({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "GFLIX",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const genres = await getGenres()
  
  return (
    <html lang="pt-BR" className="scroll-smooth">
      <body className={`${roboto.className} body`}>
        <MdbProvider>
          <Header genres={genres} />
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </MdbProvider>
      </body>
    </html>
  );
}
